kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:6c9b2dfac4ac446e57ad83e9817db4b5a334301c
  - linuxkit/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
  - linuxkit/containerd:fe1b7f438a234cb6481c6538295115eac2a0596d
services:
  - name: rngd
    image: "linuxkit/rngd:61a07ced77a9747708223ca16a4aec621eacf518"
    capabilities:
     - CAP_SYS_ADMIN
    oomScoreAdj: -800
  - name: dhcpcd
    image: "linuxkit/dhcpcd:2def74ab3f9233b4c09ebb196ba47c27c08b0ed8"
    binds:
     - /var:/var
     - /tmp:/etc
    capabilities:
     - CAP_NET_ADMIN
     - CAP_NET_BIND_SERVICE
     - CAP_NET_RAW
    net: host
    oomScoreAdj: -800
  - name: node_exporter
    image: "linuxkit/node_exporter:0c7c1588e4cbce9cc946c1a84d3902b38b4b7ada"
    capabilities:
     - all
    net: host
    pid: host
    binds:
     - /proc:/host/proc
     - /sys:/host/sys
     - /:/rootfs
trust:
  image:
    - linuxkit/kernel
    - linuxkit/rngd
outputs:
  - format: kernel+initrd
